version: '3.8'
services:
  db:
    build: ./database
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  automation:
    build: ./automation
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PW}@db:5432/${PG_DB}
    ports:
      - "3000:3000"
      
volumes:
  db_data:
