# automation/Dockerfile

# parent image
FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# EXPOSE 3000

CMD ["python", "./run_automation.py"]
